# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [ '**' ]  # You can specify branches or use 'branches: [ '**' ]' for all branches
  pull_request:
    branches: [ '**' ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Specify your Java version
          distribution: 'temurin'  # You can choose 'zulu' or others if needed

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
